### ISSUE TITLE
Roadmap for KDL 1.0

### ISSUE THREAD

**Issue by zkat** [kdl-org/kdl#112]
Alright, it's been a while, and I think it's time to have a concrete plan for tagging KDL 1.0. Once we hit that, it'll be much harder to change the language, so I want to make sure any and all major pending questions are addressed before doing that.

If you're interested in helping KDL along, please help resolve/comment on the following so we can close them out and get that 1.0.0 out the door!

* [x] https://github.com/kdl-org/kdl/issues/131
* [x] https://github.com/kdl-org/kdl/issues/105
* [x] https://github.com/kdl-org/kdl/issues/128
* [x] https://github.com/kdl-org/kdl/issues/121 
* [x] https://github.com/kdl-org/kdl/issues/106
* [x] https://github.com/kdl-org/kdl/issues/75
* [x] https://github.com/kdl-org/kdl/issues/69
* [x] https://github.com/kdl-org/kdl/issues/59
* [x] https://github.com/kdl-org/kdl/issues/113
* [x] https://github.com/kdl-org/kdl/issues/114
* [x] https://github.com/kdl-org/kdl/issues/115
* [x] https://github.com/kdl-org/kdl/issues/116

**Comment by zkat** [comment]
Alright, the list is complete. I think it's time to tag 1.0!

Any objections or last-minute changes you'd like to get in?

/cc @hkolbeck @tabatkins @larsgw @lucretiel

I'll give this until this weekend and then take care of tagging 1.0 if there's nothing else we want to go in before we hit stable :)

**Comment by tabatkins** [comment]
I'm very satisfied with this!

**Comment by ericsampson** [comment]
Cool!

I created a PR #134 to add a few more reserved type annotations, if you agree with them it'd be great to get in for the 1.0

Thanks!

**Comment by larsgw** [comment]
@zkat I still want to add the Schema for the tags but that should be done before the weekend

**Comment by larsgw** [comment]
kdljs should now support the spec changes since `v0.1.0-rc.2`.

**Comment by zkat** [comment]
It's done! and announced! Feel free to RT: https://twitter.com/zkat__/status/1436910392316289024

HUGE thanks to everyone who's been helping with all this. You've all made KDL go from a pretty basic-but-neat little something to a really exciting language I'm looking forward to using the shit out of! Now let's get all those implementations stabilized so we can do some serious marketing for this thing and take over the world!
