### ISSUE TITLE
KDL 1.0.0 compliance for implementations

### ISSUE THREAD

**Issue by zkat** [kdl-org/kdl#144]
This is a tracking meta-issue to make sure all existing implementations are up to speed with 1.0!

* [x] kdl-rs: https://github.com/kdl-org/kdl-rs/issues/18
* [x] kdljs: https://github.com/kdl-org/kdljs/issues/6
* [x] kdl-rb: https://github.com/danini-the-panini/kdl-rb/issues/2
* [x] kdl-dart: https://github.com/danini-the-panini/kdl-dart/issues/1
* [x] kdl4j: https://github.com/hkolbeck/kdl4j/issues/3
* [ ] kdl-net: https://github.com/borland/kdl-net/issues/1
* [ ] kdl-php: https://github.com/kdl-org/kdl-php/issues/22

New implementations:
* [ ] Lua: https://github.com/kdl-org/kdl/issues/145
* [x] Elixir: https://github.com/kdl-org/kdl/issues/155
* [x] C: https://github.com/kdl-org/kdl/issues/160
* [x] Go: https://github.com/kdl-org/kdl/issues/54
* [x] Python: https://github.com/tabatkins/kdlpy

Other bits:
* [x] VS Code: https://github.com/kdl-org/vscode-kdl/issues/4

**Comment by hkolbeck** [comment]
I spoke to @borland on Twitter and he'd like to wait on the Java update, then port the changes over to the .NET impl, which works for me.

**Comment by hkolbeck** [comment]
I believe kdl4j is compliant with the 1.0.0 spec as of these changes: https://github.com/hkolbeck/kdl4j/pull/4

@borland: I think the changes in that PR should be ready to port over, though they're more extensive than I'd hoped.

**Comment by djmattyg007** [comment]
I wouldn't be waiting on the original `kdl-py` implementation to be updated. Even in its current state, it's not compliant with the spec as it was written at the time. Better to just refer to `kdlpy` and `cuddle`.

**Comment by Patitotective** [comment]
I think [`kdl-nim`](https://github.com/Patitotective/kdl-nim) is already compliant with KDL v1.0.0.

**Comment by zkat** [comment]
Since we have #372 now, I'm going to close this one.
